#!/usr/bin/python3
# SPDX-FileCopyrightText: ©2023　Yuto Okuda
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0   #もともと0.0だったものを0に変更
for line in sys.stdin:
    try:
        ans += int(line)    #intは文字列を整数に（失敗すると例外処理）
    except:
        ans += float(line)

print(ans)
